# Generated by Django 5.1.5 on 2025-03-03 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('detail', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
